### ISSUE TITLE
Saxon-HE 10: NoSuchMethodError: net.sf.saxon.om.NodeInfo.iterateAxis(byte)

### ISSUE THREAD

**Issue by thms-rmb** [expath/expath-http-client-java#17]
I'm trying to use this with Saxon-HE 10.3, but I am getting a NoSuchMethodError exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'net.sf.saxon.tree.iter.AxisIterator net.sf.saxon.om.NodeInfo.iterateAxis(byte)'
	at org.expath.tools.saxon.model.SaxonElement.attributes(SaxonElement.java:95)
	at org.expath.httpclient.impl.RequestParser.parse(RequestParser.java:89)
	at org.expath.httpclient.HttpClient.doSendRequest(HttpClient.java:96)
	at org.expath.httpclient.HttpClient.sendRequest(HttpClient.java:89)
	at org.expath.httpclient.saxon.SendRequestCall.call(SendRequestCall.java:65)
	at net.sf.saxon.functions.IntegratedFunctionCall.iterate(IntegratedFunctionCall.java:293)
	at net.sf.saxon.expr.parser.Evaluator$11.evaluate(Evaluator.java:290)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:545)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:737)
	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:264)
	at net.sf.saxon.trans.XsltController.callTemplate(XsltController.java:850)
	at net.sf.saxon.s9api.Xslt30Transformer.callTemplate(Xslt30Transformer.java:480)
	at net.sf.saxon.Transform.processFile(Transform.java:1306)
	at net.sf.saxon.Transform.doTransform(Transform.java:853)
	at no.ramsen.Transform.main(Transform.java:16)
	at no.ramsen.App.main(App.java:33)
```

I believe the method signature for `net.sf.saxon.om.NodeInfo.iterateAxis` changed between Saxon 9.9 and Saxon 10, perhaps that is the cause?

- [Saxon 9.9](https://www.saxonica.com/html/documentation9.9/javadoc/net/sf/saxon/om/NodeInfo.html#iterateAxis-byte-)
- [Saxon 10](https://www.saxonica.com/html/documentation/javadoc/net/sf/saxon/om/NodeInfo.html#iterateAxis-int-)

**Comment by adamretter** [comment]
I recently updated the project for Saxon 9.9.1-7.

Would you be interested in sending a PR to update it for Saxon 10?

**Comment by thms-rmb** [comment]
@adamretter I've made an attempt:

- https://github.com/expath/expath-http-client-java/pull/18
- https://github.com/expath/expath-tools-saxon/pull/2
- https://github.com/expath/expath-parent/pull/40

**Comment by adamretter** [comment]
Thanks for your contributions @thms-rmb I have now merged your PRs and released new versions to Maven Central.
